apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-dip
  name: app-dip
  #annotations:
  #  service.beta.kubernetes.io/aws-load-balancer-type: elb
  #  service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'

spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: app-dip