apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app-dip
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-dip
  template:
    metadata:
      labels:
        app: app-dip
    spec:
      containers:
      - name: app-dip
        env:
        - name: BUILD_TIMESTAMP
          value: "{{ lookup('env', 'BUILD_TIMESTAMP') }}"
        image: alsxs/nginx:$(BUILD_TIMESTAMP)
        ports:
        - containerPort: 80
