apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app-dip
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-dip
  template:
    metadata:
      labels:
        app: app-dip
    spec:
      containers:
      - name: app-dip
        image: alsxs/nginx:alpineapp
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-dip
  name: app-dip
  #namespace: monitoring
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http
  selector:
    app: app-dip