pipeline {
    agent {
        kubernetes{
            label 'jenkins-agent1'
        }
    }
    triggers { pollSCM('* * * * *') }
    environment {
		DOCKERHUB_CREDENTIALS=credentials('37b6274a-7c9a-4b48-81f0-6aa82a13c813')
	}
    stages {

	    stage('gitclone') {
            when {
                branch 'main'
            }
			steps {

			    echo " ============== gitclone =================="
				git 'https://github.com/als-port/dip-net.git'
			}
		}

		stage('Build') {

			steps {
			    echo " ============== Build =================="
			    dir ('app') {
				    sh 'sudo docker build -t alsxs/nginx:applatest .'
				}
			}
		}

		stage('Login') {

			steps {
			    echo " ============== Dockerhub login =================="
				sh 'echo $DOCKERHUB_CREDENTIALS_PSW | sudo docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
			}
		}

		stage('Kubernetes') {
            steps {
                echo " ============== Change app-deploy =================="
                 withKubeConfig([credentialsId: '5711acea-40f4-4509-84a1-31905eefd83d', serverUrl: 'https://3F819F8F7E5C8FE3DC2DD201132A33BB.gr7.eu-central-1.eks.amazonaws.com'])  {
                    sh 'kubectl delete deploy app-deployment'
                    sh "kubectl delete app-dip"
                    sh "kubectl apply -f kube/kube_app.yaml"
                }



            }
        }


    }

}